version: "3.8"

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-webchat
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ./api/:/app/data
    depends_on:
      - db
    networks:
      - default

  db:
    image: mariadb:10.5
    container_name: db-webchat
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-webchat
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - default

  frontend:
    image: node:latest
    container_name: nodejs-webchat
    working_dir: /app
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run build && npm run start" # Buduj i uruchom aplikację
    networks:
      - default

  reverseproxy:
    image: nginx:1.27.2
    container_name: proxy-webchat
    ports:
      - "33002:443" # Next.js and API
      - "33102:33102" # phpMyAdmin
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./frontend/public:/usr/share/nginx/html/public
    depends_on:
      - webapi
      - frontend
    networks:
      - default

networks:
  default:
    driver: bridge
